### ISSUE TITLE
Cheatsheet does not distinguish members of related mutable and immutable types

### ISSUE THREAD

**Issue by jmholla** [kieranholland/best-python-cheat-sheet#2]
For instance under `Set`, methods like `discard` and `pop` do not apply to the immutable (`frozenset`) version. I'm not sure how best to distinguish this, but it could be helpful to delineate their differences.

**Comment by kieranholland** [comment]
Good point, I'll consider for next iteration.

**Comment by kieranholland** [comment]
Added [mutable] flag to mutable-only methods.
