### ISSUE TITLE
Regular Expression \d

### ISSUE THREAD

**Issue by shunsock** [kieranholland/best-python-cheat-sheet#5]
I felt that your project is wonderful. I created this issue because I thought I could contribute even a little.

## About
Python's regex can implements meta characters, but we have to use carefully when using \d, because it includes all of Unicode characters which are in category Nd.
[regex - Regular Expression](https://docs.python.org/3/library/re.html)
[List of Unicode Characters included group Nd](https://www.compart.com/en/unicode/category/Nd)

## \d's behavior
ascii mode => [0-9]
non ascii mode => all of characters which in category Nd

> For Unicode (str) patterns: 
Matches any Unicode decimal digit (that is, any character in Unicode character category [[Nd]](https://www.unicode.org/versions/Unicode15.0.0/ch04.pdf#G134153)). This includes [0-9], and also many other digit characters. 
Matches [0-9] if the [ASCII](https://docs.python.org/3/library/re.html#re.ASCII) flag is used.

[regex - Regular Expression](https://docs.python.org/3/library/re.html)

## Why I created this
I think people who is not accustomed to regex can think it only includes [0-9] by default. However we have to set ascii flag. This is significant when creating validation for user id or password.

## Reccomendation
- Before
> \d Decimal digit

- After
> \d Matches any characters in Unicode Number, decimal digit category. This include not only [0-9].

**Comment by kieranholland** [comment]
Thanks, I have added ASCII flag.
