### ISSUE TITLE
On macOS, Courier New is razor thin and hard to read

### ISSUE THREAD

**Issue by nicktimko** [kieranholland/best-python-cheat-sheet#6]
On macOS, Courier New is razor thin and hard to read. 

You could link the [Google WebFont version of Roboto Mono](https://fonts.google.com/specimen/Roboto+Mono) by adding

```
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Roboto+Mono:ital,wght@0,100..700;1,100..700&display=swap" rel="stylesheet">
```

or 

```
<style>
@import url('https://fonts.googleapis.com/css2?family=Roboto+Mono:ital,wght@0,100..700;1,100..700&display=swap')
</style>
```

to the `<head>`

**Comment by shunsock** [comment]
I think so. Here's what the site looks like with MacOS.
![screes shot](https://github.com/kieranholland/best-python-cheat-sheet/assets/84004458/9b35373b-0798-4d5b-be37-aea5107ce4a0)

**Comment by kieranholland** [comment]
Added Google webfont, let me know if it doesn't work.
