### ISSUE TITLE
NamedTuple notes.

### ISSUE THREAD

**Issue by killrpenguin** [kieranholland/best-python-cheat-sheet#9]
This is an awesome cheet-sheet Very helpful, thank you. I don't think what I've found is a mistake, but maybe a small way to add more info. 

The notes on named Tuple call collections.namedtuple. There is a newer typed version of NamedTuple under typing.NamedTuple. I am having a hard time finding the docs.python page for you but I found the [dev-docs page](https://devdocs.io/python~3.12/library/typing#typing.NamedTuple) for it. Might be worth a look.

**Comment by kieranholland** [comment]
Added link to this thanks
